# Generated by Django 5.1.6 on 2025-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
