# Generated by Django 5.1.6 on 2025-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_cartype_remove_car_make_remove_car_model_carpart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('IN_SERVICE', 'In Service'), ('NO_SERVICE', 'No Service')], default='IN_SERVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
