# Generated by Django 5.1.6 on 2025-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_remove_repair_finished_at_remove_repair_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='in_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
