# Generated by Django 5.1.6 on 2025-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_carpart_price_repair_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('IN_SERVICE', 'In Service'), ('NO_SERVICE', 'No Service')], default='NO_SERVICE', max_length=20),
        ),
    ]
