name: "Build project"
description: "Action to build the project"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up Python
      if: ${{ !env.ACT }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        pip install poetry
        poetry install --with dev --no-root

    - name: Run Django tests with mocks
      shell: bash
      run: |
        poetry run coverage run -m pytest --nomigrations --reuse-db
        poetry run coverage report
        poetry run coverage html
        poetry run coverage-badge -o coverage.svg -f

    - name: Move badge to badges/
      shell: bash
      run: mv coverage.svg badges/
