name: "Build project"
description: "Action to build the project"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run Django tests
      shell: bash
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
      run: poetry run python manage.py test
