name: "Build project"
description: "Action to build the project"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up Python
      if: ${{ !env.ACT }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        pip install poetry
        poetry install --with dev --no-root

    - name: Run Django tests with mocks
      shell: bash
      run: |
        echo "Running tests with mocks..."
        poetry run pytest --nomigrations --reuse-db
