name: Build and Push Docker Image

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        uses: ./.github/actions/run_unit_tests
        with:
          github_token: ${GITHUB_TOKEN}

  build:
    name: build application
    needs:
      - test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: build application
        uses: ./.github/actions/build
        with:
          docker_hub_access_token: ${DOCKER_HUB_ACCESS_TOKEN}
          docker_hub_username: ${DOCKER_HUB_USERNAME}
