name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test  # Waits for the test job to pass before running

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kaniko
        uses: imjasonh/setup-kaniko@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo "${DOCKER_HUB_ACCESS_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
          /kaniko/executor --context . --dockerfile ops/Dockerfile --destination "${DOCKER_HUB_USERNAME}/crm-app:latest"
